export {
  decileBundleSubIds,
  decileBundleSubIdsForLoad,
  getDecileBundleConfig,
  isDecileBundleVariable,
  isOecdDecileBundleVariable,
  isPipDecileBundleVariable,
  isWdiQuintileBundleVariable,
  labelForDecileBundleSub,
  OECD_DECILE_BUNDLE_ID,
  OECD_DECILE_RATIO_IDS,
  OECD_DECILE_RATIO_OPTIONS,
  PIP_DECILE_BUNDLE_ID,
  PIP_DECILE_IDS,
  PIP_DECILE_OPTIONS,
  WDI_QUINTILE_BUNDLE_ID,
  WDI_QUINTILE_IDS,
  WDI_QUINTILE_OPTIONS,
  type DecileBundleConfig,
  type DecileBundleOption,
} from '@domain/catalog/decileBundles'
